require("dotenv").config();
const mongoose = require("mongoose");
const Product = require("../modules/products/Product");

const RESTORE_DATA = [
  [
    { name: "Tog'ora 1 sort 12 L", qty: 475, unit: "DONA" },
    { name: "Kosa piston 1 L", qty: 161, unit: "DONA" },
    { name: "Kosa piston 3 L", qty: 161, unit: "DONA" },
    { name: "Bumaga derjatel oddiy", qty: 150, unit: "DONA" },
    { name: "Patnus imron katta", qty: 60, unit: "DONA" },
    { name: "Patnus imron kichik", qty: 100, unit: "DONA" },
    { name: "Tog'ora 1.5 sort 10 L", qty: 101, unit: "DONA" },
    { name: "Chomich kaska", qty: 574, unit: "DONA" },
    { name: "Tuzdon", qty: 3, unit: "DONA" },
    { name: "Paqir 1 sort 12 L F", qty: 71, unit: "DONA" },
    { name: "Paqir krishka 2 sort 12 L", qty: 83, unit: "DONA" },
    { name: "Kurak barg", qty: 87, unit: "DONA" },
    { name: "Anor jom 8.5 L", qty: 125, unit: "DONA" },
    { name: "Xol xol 5.5 L dumaloq", qty: 133, unit: "DONA" },
    { name: "Xol xol 5.5 L tortburchak", qty: 34, unit: "DONA" },
    { name: "Murabbo idish 1", qty: 401, unit: "DONA" },
    { name: "Sovun quti 2", qty: 161, unit: "DONA" },
    { name: "Jemchuk katta", qty: 175, unit: "DONA" },
    { name: "Anor jom 2.5 L", qty: 93, unit: "DONA" },
    { name: "Hol hol 3 l", qty: 12, unit: "DONA" },
    { name: "Gofra", qty: 30, unit: "DONA" },
    { name: "Paqir 5 L F", qty: 87, unit: "DONA" },
    { name: "Paqir 15 L F", qty: 243, unit: "DONA" },
    { name: "Krujka yapon", qty: 320, unit: "DONA" },
    { name: "Krujka romashka", qty: 382, unit: "DONA" },
    { name: "Kampot qapqoq", qty: 4202, unit: "DONA" },
    { name: "Jemchuk kichik", qty: 460, unit: "DONA" },
    { name: "Fresh karzinka", qty: 325, unit: "DONA" },
    { name: "Paqir 8 L F", qty: 124, unit: "DONA" },
    { name: "Paqir milano 12 L", qty: 193, unit: "DONA" },
    { name: "Paqir milano 10 L", qty: 221, unit: "DONA" },
    { name: "Sovun quti 1", qty: 50, unit: "DONA" },
    { name: "Salfetnisa 1", qty: 195, unit: "DONA" },
    { name: "Romashka jom 3 L", qty: 283, unit: "DONA" },
    { name: "Romashka jom 4 L", qty: 413, unit: "DONA" },
    { name: "Romashka jom 8 L", qty: 190, unit: "DONA" },
    { name: "Sariyog' idish", qty: 205, unit: "DONA" },
    { name: "Anor jom 4 L", qty: 55, unit: "DONA" },
    { name: "Anor jom 6 L", qty: 164, unit: "DONA" },
    { name: "Karzinka meva", qty: 175, unit: "DONA" },
    { name: "Xol xol 4 L", qty: 18, unit: "DONA" },
    { name: "Krujka gofra", qty: 1667, unit: "DONA" },
    { name: "Kosa ananas", qty: 331, unit: "DONA" },
    { name: "Vishilka ramka", qty: 30, unit: "DONA" },
    { name: "Is kaltak 1.5 li", qty: 95, unit: "DONA" },
    { name: "Shupurgi", qty: 45, unit: "DONA" },
    { name: "Salfetnisa  2", qty: 64, unit: "DONA" },
    { name: "Global jom 8 L", qty: 167, unit: "DONA" },
    { name: "Tog'ora 90 l", qty: 1, unit: "DONA" },
    { name: "Global jom 3.5 L", qty: 155, unit: "DONA" },
    { name: "Global jom 6.5 L", qty: 141, unit: "DONA" },
    { name: "Tog'ora", qty: 6, unit: "DONA" },
    { name: "Paqir 18 L b/k", qty: 40, unit: "DONA" },
    { name: "Salfetnisa 3", qty: 150, unit: "DONA" },
    { name: "Global jom 9 L", qty: 165, unit: "DONA" },
    { name: "Paqir 12 L b/k", qty: 52, unit: "DONA" },
    { name: "Jom 4 L T", qty: 212, unit: "DONA" },
    { name: "Paqir 15 L b/k", qty: 69, unit: "DONA" },
    { name: "Paqir 10 L b/k", qty: 53, unit: "DONA" },
    { name: "Jom 6 L T", qty: 120, unit: "DONA" },
    { name: "Kantiner rum 4 L", qty: 65, unit: "DONA" },
    { name: "Urna 3", qty: 74, unit: "DONA" },
    { name: "Qoshiqdon katta", qty: 5, unit: "DONA" },
    { name: "MIska kroshka", qty: 168, unit: "DONA" },
    { name: "Patnus gullik kich", qty: 163, unit: "DONA" },
    { name: "Banka 3 L", qty: 97, unit: "DONA" },
    { name: "Qoshiqdon tortma kichik", qty: 95, unit: "DONA" },
    { name: "Urna kalso", qty: 463, unit: "DONA" },
    { name: "Sovog'", qty: 101, unit: "DONA" },
    { name: "Krem jom katta", qty: 94, unit: "DONA" },
    { name: "Miska 3.5 L dum", qty: 33, unit: "DONA" },
    { name: "Tog'ora kvd boy", qty: 227, unit: "DONA" },
    { name: "Kantiner burger", qty: 54, unit: "DONA" },
    { name: "Kantiner 850 ml", qty: 35, unit: "DONA" },
    { name: "Xlebnitsa", qty: 5, unit: "DONA" },
    { name: "Qoshiqdon kema", qty: 62, unit: "DONA" },
    { name: "Kantiner supper 4 talik", qty: 36, unit: "DONA" },
    { name: "Garshu egar", qty: 32, unit: "DONA" },
    { name: "Patnus qizil kichik", qty: 20, unit: "DONA" },
    { name: "Banka rum 2 L", qty: 184, unit: "DONA" },
    { name: "Qoshiqdon tortma katta", qty: 77, unit: "DONA" },
    { name: "Garshu karobkalik", qty: 16, unit: "DONA" },
    { name: "Garshu bembi", qty: 122, unit: "DONA" },
    { name: "Xlebnitsa oval", qty: 252, unit: "DONA" },
    { name: "Krem jom kich", qty: 64, unit: "DONA" },
    { name: "Qoshiqdon", qty: 6, unit: "DONA" },
    { name: "Patnus qizil katta", qty: 149, unit: "DONA" },
    { name: "Miska tortburchak kichik", qty: 140, unit: "DONA" },
    { name: "Vanna bolajon", qty: 136, unit: "DONA" },
    { name: "Chelak 8 l", qty: 8, unit: "DONA" },
    { name: "Banka rum 1 L", qty: 175, unit: "DONA" },
    { name: "Banka rum 2.5 L", qty: 71, unit: "DONA" },
    { name: "Kantiner 450 ml", qty: 114, unit: "DONA" },
    { name: "Qirg'ich jom", qty: 70, unit: "DONA" },
    { name: "Xleb 10 l", qty: 8, unit: "DONA" },
    { name: "Kantiner 30 L best", qty: 49, unit: "DONA" },
    { name: "Kantiner 100 L best", qty: 85, unit: "DONA" },
    { name: "Kantiner 45 l", qty: 13, unit: "DONA" },
    { name: "Tortnisa", qty: 26, unit: "DONA" },
    { name: "Qalamdon 2", qty: 329, unit: "DONA" },
    { name: "Jemchuk smile kich", qty: 400, unit: "DONA" },
    { name: "Chumich delfin", qty: 450, unit: "DONA" },
    { name: "Karzinka universal", qty: 138, unit: "DONA" },
    { name: "Kantiner 35 L bak", qty: 15, unit: "DONA" },
    { name: "Qalamdon 1", qty: 131, unit: "DONA" },
    { name: "Kantiner 20 L best", qty: 55, unit: "DONA" },
    { name: "Kantiner 40 L best", qty: 43, unit: "DONA" },
    { name: "Kantiner 30 l", qty: 7, unit: "DONA" },
    { name: "Jemchuk smile katta", qty: 310, unit: "DONA" },
    { name: "Kantiner 60 L best", qty: 73, unit: "DONA" },
    { name: "Chotka dazmol 2", qty: 392, unit: "DONA" },
    { name: "Bumaga derjatel arqon", qty: 210, unit: "DONA" },
    { name: "Bumaga derjatel tosh", qty: 97, unit: "DONA" },
    { name: "Basket katta", qty: 45, unit: "DONA" },
    { name: "Jom 2 L", qty: 28, unit: "DONA" },
    { name: "Paqir 10 L p p", qty: 45, unit: "DONA" },
    { name: "Kosa smile katta tortburchak", qty: 250, unit: "DONA" },
    { name: "Kosa smile kichik tortburchak", qty: 55, unit: "DONA" },
    { name: "Matrushka arqon", qty: 20, unit: "DONA" },
    { name: "Qoshiqdon arzon", qty: 112, unit: "DONA" },
    { name: "Jom ilyos 2 L", qty: 280, unit: "DONA" },
    { name: "Paqir 5 L p p", qty: 121, unit: "DONA" },
    { name: "Kosa smile katta dumaloq", qty: 125, unit: "DONA" },
    { name: "Basket kichik", qty: 18, unit: "DONA" },
    { name: "Lola turbo krishka", qty: 85, unit: "DONA" },
    { name: "Jom lola oddiy", qty: 56, unit: "DONA" },
    { name: "Urna arqon", qty: 81, unit: "DONA" },
    { name: "Urna setka", qty: 242, unit: "DONA" },
    { name: "Xleb big bos", qty: 49, unit: "DONA" },
    { name: "Xlebnisa p p katta", qty: 31, unit: "DONA" },
    { name: "Kosa arqon 3", qty: 140, unit: "DONA" },
    { name: "Patnus", qty: 13, unit: "DONA" },
    { name: "Turbo p p b/k", qty: 124, unit: "DONA" },
    { name: "Krujka ilyos kichik", qty: 260, unit: "DONA" },
    { name: "Paqir 3 L p p", qty: 132, unit: "DONA" },
    { name: "Chelak 4 l", qty: 14, unit: "DONA" },
    { name: "Unitaz oq", qty: 27, unit: "DONA" },
    { name: "Tog'ora 170 l", qty: 2, unit: "DONA" },
    { name: "Chelak 10 l", qty: 4, unit: "DONA" },
    { name: "Qoqon 16 l", qty: 9, unit: "DONA" },
    { name: "Kosa oddiy 1 L", qty: 222, unit: "DONA" },
    { name: "Turbo kichik 1.5 L", qty: 408, unit: "DONA" },
    { name: "Meva karzinka", qty: 325, unit: "DONA" },
    { name: "Vishilka yog'och", qty: 8, unit: "DONA" },
    { name: "Tabretka temir katta", qty: 16, unit: "DONA" },
    { name: "Tabretka temir kichik", qty: 24, unit: "DONA" },
  ],
];

async function restore() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log("♻️ RESTORE STARTED");

  for (const item of RESTORE_DATA) {
    const p = await Product.findOne({ name: item.name });

    if (!p) {
      console.log("❌ TOPILMADI:", item.name);
      continue;
    }

    await Product.updateOne({ _id: p._id }, { $set: { qty: item.qty } });

    console.log(`✅ ${item.name}: ${item.qty}`);
  }

  console.log("♻️ RESTORE FINISHED");
  process.exit();
}

restore().catch((err) => {
  console.error("❌ ERROR:", err);
  process.exit(1);
});
